# Антонина Зацепина. МИВТ-23-9. ДЗ по numpy

# Задание 1

In [ ]:
Видео с восхищением просмотрены.

In [2]:
import numpy as np

# Задание 2

Список чисел: при наличие десятичного, все целые так же преобразуются в десятичные.

In [27]:
lst_of_nums = [1, 2.2, .33]
nums_values = np.array(lst_of_nums)
lst_of_nums, nums_values

([1, 2.2, 0.33], array([1.  , 2.2 , 0.33]))

In [28]:
type(lst_of_nums), type(nums_values)

(list, numpy.ndarray)

In [29]:
nums_values.dtype

dtype('float64')

Смешанный список: при наличие строкового значения, все преобразуются к str

In [30]:
lst_of_mix = ["1", 2.2, .33]
str_values = np.array(lst_of_mix)
lst_of_mix, str_values

(['1', 2.2, 0.33], array(['1', '2.2', '0.33'], dtype='<U32'))

In [31]:
type(lst_of_mix), type(str_values)

(list, numpy.ndarray)

In [32]:
str_values.dtype

dtype('<U32')

Булевые значения

In [33]:
lst_of_bools = [1, True, 0, False]
bool_values = np.array(lst_of_bools)
lst_of_bools, bool_values

([1, True, 0, False], array([1, 1, 0, 0]))

In [34]:
type(lst_of_bools), type(bool_values)

(list, numpy.ndarray)

In [35]:
bool_values.dtype

dtype('int32')

# Задание 3

In [47]:
var1 = np.array([2, 4, 6, 8, 10, 12]) #явно
var1

array([ 2,  4,  6,  8, 10, 12])

In [48]:
var2 = np.arange(2, 13, 2) #начало, конец, шаг
var2

array([ 2,  4,  6,  8, 10, 12])

In [49]:
var3 = np.linspace(2, 12, 6) #начало, конец, количество элементов
var3

array([ 2.,  4.,  6.,  8., 10., 12.])

# Задание 4

In [51]:
d2_var1 = var1.reshape(2, 3)
d2_var1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
d2_var2 = var2.reshape(3, 2)
d2_var2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [53]:
d2_var3 = var3.reshape(-1, 1)
d2_var3

array([[ 2.],
       [ 4.],
       [ 6.],
       [ 8.],
       [10.],
       [12.]])

# Задание 5

In [55]:
var2 = np.arange(2, 13, 2.2) #начало, конец, шаг
var2

array([ 2. ,  4.2,  6.4,  8.6, 10.8])

# Задание 6

In [61]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [62]:
np.vstack([v1, v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6])

# Задание 7

In [77]:
a = np.fromiter(range(20), dtype='float').reshape(2,2,5)
b = np.fromiter(range(20, 30), dtype='float').reshape(1,2,5)

a.shape, b.shape

((2, 2, 5), (1, 2, 5))

In [78]:
np.vstack([a,b]).shape 
#vstack соединяет по первому измерению, остальные размерности векторов должны совпадать

(3, 2, 5)

# Задание 8

In [79]:
A = np.array([[1, 5, 8], [5, 7, 2], [4, 7, 9]])
b = np.array([89, 90, 3])
np.linalg.solve(A, b)

array([-65.1625,  65.6125, -21.7375])

In [81]:
np.linalg.inv(A) @ b 

array([-65.1625,  65.6125, -21.7375])

# Задание 9

In [3]:
for_types = np.array([1, 2, 3, 4])
for_types

array([1, 2, 3, 4])

In [8]:
type1 = np.array(for_types, dtype=np.float16)
type1

array([1., 2., 3., 4.], dtype=float16)

In [9]:
type2 = np.array(for_types, dtype='float32')
type2

array([1., 2., 3., 4.], dtype=float32)

In [11]:
type3 = np.array(for_types, dtype='str_')
type3

array(['1', '2', '3', '4'], dtype='<U11')

# Задание 10

In [19]:
x = np.arange(16).reshape((8,2,1))
x.shape

(8, 2, 1)

In [20]:
x.squeeze().shape #выпихивает единичные измерния

(8, 2)

# Задание 11

In [49]:
x3 = np.arange(24).reshape((4,3,2))
x3.shape

(4, 3, 2)

In [50]:
x5 = x3[np.newaxis, :, :, None, :]
x5.shape

(1, 4, 3, 1, 2)

In [51]:
x6 = np.expand_dims(x5, axis=5)
x6.shape

(1, 4, 3, 1, 2, 1)

# Задание 12

In [52]:
A = np.array([[1, 5, 8], [5, 7, 2], [4, 7, 9]])
B = np.array([[6, 4, 3], [2, 3, 7], [4, 2, 1]])

In [53]:
A2 = A*2
A2

array([[ 2, 10, 16],
       [10, 14,  4],
       [ 8, 14, 18]])

In [54]:
C = A + B
C

array([[ 7,  9, 11],
       [ 7, 10,  9],
       [ 8,  9, 10]])

In [55]:
C1 = A*B #поточечное умножение
C1

array([[ 6, 20, 24],
       [10, 21, 14],
       [16, 14,  9]])

In [56]:
C2 = A@B #умножение здорового человека
C2

array([[48, 35, 46],
       [52, 45, 66],
       [74, 55, 70]])

In [60]:
b = np.array([1, 2, 3]).reshape(-1, 1)
C3 = A@b
C3

array([[35],
       [25],
       [45]])

# Задание 13

In [82]:
def matrix_multiplication(A: np.array, B: np.array):
    C = np.zeros((A.shape[0], B.shape[1]))
    if A.shape[1] != B.shape[0]:
        print("Количество столбцов в первой матрице не совпадает с количеством строк во второй - умножение невозможно.")
    else:
        for n in range(A.shape[0]):
            for k in range(B.shape[1]):
                for m in range(A.shape[1]):
                    C[n][k] += A[n][m]*B[m][k]
    return C

In [86]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = matrix_multiplication(A, B)
C             

array([[22., 28.],
       [49., 64.]])

In [81]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A@B
C 

array([[22, 28],
       [49, 64]])

# Задание 14

In [87]:
%%timeit
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = matrix_multiplication(A, B)
C             

21.1 µs ± 2.61 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [88]:
%%timeit
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A@B
C 

5.88 µs ± 349 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# встроенный метод в ~4 раза быстрее, т.к. написан вероятно на С++

# Задание 15

In [93]:
v1 = np.array([3, 2]) # был вектор с координатами (3,2)
m1 = np.array([[0, 2], [-1, 0]]) # плоскость повернули на 90 по часовой и растянули в 2 раза по оси х (i(0, -1), j(2, 0))
v1_rez = m1@v1 # трансформировали вектор
v1_rez

array([ 4, -3])

In [94]:
v2 = np.array([2, 1, 3])
m2 = np.array([[1, 0, 0], [0, 1, 1], [0, 0, 1]]) # у коробочки съехала крыша на 1 по у
v2_rez = m2@v2
v2_rez

array([2, 4, 3])

In [95]:
v3 = np.array([1, 1])
m3 = np.array([[1, 0], [0, 3]]) # выросли на 3 по y
m4 = np.array([[1, 0], [1, 3]]) # подняли i в (1, 1)
v3_rez = m4@m3@v3 
v3_rez

array([ 1, 10])